services:
  nginx:
    build:
      dockerfile: nginx/nginx.dockerfile
      context: .
    container_name: nginx
    network_mode: host
    volumes:
      - ./client/dist:/app/www/
    restart: always
