version: "2"

services:
  client:
    build:
      dockerfile: client.dockerfile
      context: client
    volumes:
      - client:/app/dist
  server:
    build:
      dockerfile: server.dockerfile
      context: server
    ports:
      - 6106:6006
    environment:
      DATABASE_URL: "sqlite:db/database.sqlite3"
    volumes:
      - ./db:/db
  nginx:
    build:
      dockerfile: nginx.dockerfile
      context: nginx
    ports:
      - 8000:80
    volumes:
      - client:/app/dist
volumes:
  client:
