services:
  client:
    build:
      dockerfile: client.dockerfile
      context: client
    image: ghcr.io/thomas-delalande/tiny-poker-client
    container_name: client
    volumes:
      - client:/app/dist
  server:
    build:
      dockerfile: server.dockerfile
      context: server
    image: ghcr.io/thomas-delalande/tiny-poker-server
    environment:
      DATABASE_URL: "sqlite:db/database.sqlite3"
    ports:
      - "6006"
    volumes:
      - ./db:/db
    restart: always
  nginx:
    build:
      dockerfile: nginx.dockerfile
      context: nginx
    image: ghcr.io/thomas-delalande/tiny-poker-nginx
    container_name: nginx
    ports:
      - 9029:80
    volumes:
      - client:/app/dist
    restart: always
    depends_on:
      - server
volumes:
  client:
