services:
  nginx:
    build:
      dockerfile: nginx/nginx.dockerfile
      context: .
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/app/nginx.conf/:ro
      - ./client/dist:/app/www/app/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - server
      - client
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
  server:
    build:
      context: server
      dockerfile: server.dockerfile
    environment:
      - PORT=9001
      - BUILD_VERSION=${BUILD_VERSION}
    volumes:
      - ./server/db:/app/db
    restart: always
  client:
    build:
      context: client
      dockerfile: client.dockerfile
    environment:
      - BUILD_VERSION=${BUILD_VERSION}
    container_name: client
    volumes:
      - ./client/dist:/app/dist
