name: Deploy
run-name: ${{ github.actor }} merged into main 🚀
on:
  push:
    branches:
      - main
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker-compose.yaml
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
      #     chmod 600 ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa.pub
      # - name: Deploy
      #   run: |
      #     ssh ${{ secrets.SERVER_IP_ADDRESS }} "/app/deploy.sh"
