name: Deploy
run-name: ${{ github.actor }} merged into main 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: docker-compose up
      - name: Publish docker images
        run: docker push ghcr.io/thomas-delalande/poker-server:latest
      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
      #     chmod 600 ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa.pub
      # - name: Deploy
      #   run: |
      #     ssh ${{ secrets.SERVER_IP_ADDRESS }} "/app/deploy.sh"

